mkdir 10_-_Onthophagus_taurus_training; cd 10_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 11_-_Onthophagus_taurus_training; cd 11_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 12_-_Onthophagus_taurus_training; cd 12_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 13_-_Onthophagus_taurus_training; cd 13_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 14_-_Onthophagus_taurus_training; cd 14_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 15_-_Onthophagus_taurus_training; cd 15_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 16_-_Onthophagus_taurus_training; cd 16_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 17_-_Onthophagus_taurus_training; cd 17_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 18_-_Onthophagus_taurus_training; cd 18_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 19_-_Onthophagus_taurus_training; cd 19_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 1_-_Onthophagus_taurus_training; cd 1_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 20_-_Onthophagus_taurus_training; cd 20_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 21_-_Onthophagus_taurus_training; cd 21_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 22_-_Onthophagus_taurus_training; cd 22_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 23_-_Onthophagus_taurus_training; cd 23_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 24_-_Onthophagus_taurus_training; cd 24_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 25_-_Onthophagus_taurus_training; cd 25_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 26_-_Onthophagus_taurus_training; cd 26_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 27_-_Onthophagus_taurus_training; cd 27_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 28_-_Onthophagus_taurus_training; cd 28_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 29_-_Onthophagus_taurus_training; cd 29_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 2_-_Onthophagus_taurus_training; cd 2_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 30_-_Onthophagus_taurus_training; cd 30_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 31_-_Onthophagus_taurus_training; cd 31_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 32_-_Onthophagus_taurus_training; cd 32_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 33_-_Onthophagus_taurus_training; cd 33_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 34_-_Onthophagus_taurus_training; cd 34_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 35_-_Onthophagus_taurus_training; cd 35_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 36_-_Onthophagus_taurus_training; cd 36_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 37_-_Onthophagus_taurus_training; cd 37_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 38_-_Onthophagus_taurus_training; cd 38_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 39_-_Onthophagus_taurus_training; cd 39_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 3_-_Onthophagus_taurus_training; cd 3_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 40_-_Onthophagus_taurus_training; cd 40_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 4_-_Onthophagus_taurus_training; cd 4_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 5_-_Onthophagus_taurus_training; cd 5_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 6_-_Onthophagus_taurus_training; cd 6_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 7_-_Onthophagus_taurus_training; cd 7_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 8_-_Onthophagus_taurus_training; cd 8_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 9_-_Onthophagus_taurus_training; cd 9_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir Aethina_tumida; cd Aethina_tumida; cp /app/data/other_species/aettum/jbrowse/data/trackList.json .; cd .. 
mkdir Agrilus_planipennis; cd Agrilus_planipennis; cp /app/data/BCM_i5k_pilot/agrpla/jbrowse/data/trackList.json .; cd .. 
mkdir Amyelois_transitella; cd Amyelois_transitella; cp /app/data/other_species/amytra/jbrowse/data/trackList.json .; cd .. 
mkdir Anoplophora_glabripennis; cd Anoplophora_glabripennis; cp /app/data/BCM_i5k_pilot/anogla/BCM/jbrowse/data/trackList.json .; cd .. 
mkdir Apis_mellifera; cd Apis_mellifera; cp /app/data/other_species/apimel/Amel_4.5/jbrowse/data//trackList.json .; cd .. 
mkdir Athalia_rosae; cd Athalia_rosae; cp /app/data/BCM_i5k_pilot/athros/BCM/jbrowse/data/trackList.json .; cd .. 
mkdir Bactrocera_cucurbitae; cd Bactrocera_cucurbitae; cp /app/data/other_species/baccuc/jbrowse/data/trackList.json .; cd .. 
mkdir Bactrocera_dorsalis; cd Bactrocera_dorsalis; cp /app/data/other_species/bacdor/jbrowse/data/trackList.json .; cd .. 
mkdir Bactrocera_oleae; cd Bactrocera_oleae; cp /app/data/other_species/bacole/jbrowse/data/trackList.json .; cd .. 
mkdir Bemisia_tabaci; cd Bemisia_tabaci; cp /app/data/other_species/bemtab/jbrowse/data/trackList.json .; cd .. 
mkdir Blattella_germanica; cd Blattella_germanica; cp /app/data/BCM_i5k_pilot/blager/BCM/jbrowse/data/trackList.json .; cd .. 
mkdir Bombus_impatiens; cd Bombus_impatiens; cp /app/data/other_species/bomimp/BIMP_2.1/jbrowse/data/trackList.json .; cd .. 
mkdir Bombus_terrestris; cd Bombus_terrestris; cp /app/data/other_species/bomter/Bter_1.0/jbrowse/data/trackList.json .; cd .. 
mkdir Bradysia_coprophila; cd Bradysia_coprophila; cp /app/data/other_species/bracop/BU_Bcop_v1/jbrowse/data/trackList.json .; cd .. 
mkdir Catajapyx_aquilonaris; cd Catajapyx_aquilonaris; cp /app/data/BCM_i5k_pilot/cataqu/jbrowse/data/trackList.json .; cd .. 
mkdir Centruroides_sculpturatus; cd Centruroides_sculpturatus; cp /app/data/BCM_i5k_pilot/censcu/jbrowse/data/trackList.json .; cd .. 
mkdir Cephus_cinctus; cd Cephus_cinctus; cp /app/data/other_species/cepcin/Ccin1/jbrowse/data//trackList.json .; cd .. 
mkdir Ceratitis_capitata; cd Ceratitis_capitata; cp /app/data/BCM_i5k_pilot/cercap/jbrowse/data/trackList.json .; cd .. 
mkdir Chelonus_insularis; cd Chelonus_insularis; cp /app/data/other_species/cheins/ASM1335770v1/jbrowse/data/trackList.json .; cd .. 
mkdir Cimex_lectularius; cd Cimex_lectularius; cp /app/data/BCM_i5k_pilot/cimlec/BCM/jbrowse/data/trackList.json .; cd .. 
mkdir Clitarchus_hookeri; cd Clitarchus_hookeri; cp /app/data/other_species/clihoo/jbrowse/data/trackList.json .; cd .. 
mkdir Contarinia_nasturtii; cd Contarinia_nasturtii; cp /app/data/other_species/connas/AAFC_CNas_1.1/jbrowse/data/trackList.json .; cd .. 
mkdir Copidosoma_floridanum; cd Copidosoma_floridanum; cp /app/data/BCM_i5k_pilot/copflo/jbrowse/data/trackList.json .; cd .. 
mkdir Diabrotica_virgifera_training; cd Diabrotica_virgifera_training; cp /app/data/other_species/diavir/Dvir_v2.0_RefSeq/jbrowse/data/trackList.json .; cd .. 
mkdir Diachasma_alloeum; cd Diachasma_alloeum; cp /app/data/other_species/diaall/Dall2.0/jbrowse/data/trackList.json .; cd .. 
mkdir Diaphorina_citri; cd Diaphorina_citri; cp /app/data/other_species/diacit/jbrowse/data/trackList.json .; cd .. 
mkdir Diaphorina_citri_legacy; cd Diaphorina_citri_legacy; cp /app/data/other_species/diacit_legacy/jbrowse/data/trackList.json .; cd .. 
mkdir Drosophila_biarmipes; cd Drosophila_biarmipes; cp /app/data/modencode/drobia/Dbia_2.0/jbrowse/data/trackList.json .; cd .. 
mkdir Drosophila_bipectinata; cd Drosophila_bipectinata; cp /app/data/modencode/drobip/Dbip_2.0/jbrowse/data/trackList.json .; cd .. 
mkdir Drosophila_elegans; cd Drosophila_elegans; cp /app/data/modencode/droele/Dele_2.0/jbrowse/data/trackList.json .; cd .. 
mkdir Drosophila_eugracilis; cd Drosophila_eugracilis; cp /app/data/modencode/droeug/Deug_2.0/jbrowse/data/trackList.json .; cd .. 
mkdir Drosophila_ficusphila; cd Drosophila_ficusphila; cp /app/data/modencode/drofic/Dfic_2.0/jbrowse/data/trackList.json .; cd .. 
mkdir Drosophila_kikkawai; cd Drosophila_kikkawai; cp /app/data/modencode/drokik/Dkik_2.0/jbrowse/data/trackList.json .; cd .. 
mkdir Drosophila_rhopaloa; cd Drosophila_rhopaloa; cp /app/data/modencode/drorho/Drho_2.0/jbrowse/data/trackList.json .; cd .. 
mkdir Drosophila_takahashii; cd Drosophila_takahashii; cp /app/data/modencode/drotak/Dtak_2.0/jbrowse/data/trackList.json .; cd .. 
mkdir Dufourea_novaeangliae; cd Dufourea_novaeangliae; cp /app/data/other_species/dufnov/jbrowse/data/trackList.json .; cd .. 
mkdir Ephemera_danica; cd Ephemera_danica; cp /app/data/BCM_i5k_pilot/ephdan/Edan_2.0/jbrowse/data//trackList.json .; cd .. 
mkdir Eufriesea_mexicana; cd Eufriesea_mexicana; cp /app/data/other_species/eufmex/ASM148370v1/jbrowse/data/trackList.json .; cd .. 
mkdir Euglossa_dilemma; cd Euglossa_dilemma; cp /app/data/other_species/eugdil/jbrowse/data/trackList.json .; cd .. 
mkdir Eurytemora_affinis; cd Eurytemora_affinis; cp /app/data/BCM_i5k_pilot/euraff/jbrowse/data/trackList.json .; cd .. 
mkdir Eurytemora_affinis_-_training; cd Eurytemora_affinis_-_training; cp /app/data/BCM_i5k_pilot/euraff/jbrowse/data/trackList.json .; cd .. 
mkdir Fopius_arisanus; cd Fopius_arisanus; cp /app/data/other_species/fopari/jbrowse/data/trackList.json .; cd .. 
mkdir Frankliniella_occidentalis; cd Frankliniella_occidentalis; cp /app/data/BCM_i5k_pilot/fraocc/Focc_3.0/jbrowse/data/trackList.json .; cd .. 
mkdir Galleria_mellonella; cd Galleria_mellonella; cp /app/data/other_species/galmel/ASM364042v2/jbrowse/data/trackList.json .; cd .. 
mkdir Gerris_buenoi; cd Gerris_buenoi; cp /app/data/BCM_i5k_pilot/gerbue/jbrowse/data//trackList.json .; cd .. 
mkdir Habropoda_laboriosa; cd Habropoda_laboriosa; cp /app/data/other_species/hablab/jbrowse/data/trackList.json .; cd .. 
mkdir Halyomorpha_halys; cd Halyomorpha_halys; cp /app/data/BCM_i5k_pilot/halhal/Hhal_1.1/jbrowse/data/trackList.json .; cd .. 
mkdir Heliothis_virescens; cd Heliothis_virescens; cp /app/data/other_species/helvir/jbrowse/data//trackList.json .; cd .. 
mkdir Holacanthella_duospinosa; cd Holacanthella_duospinosa; cp /app/data/other_species/holduo/ASM273828v1/jbrowse/data/trackList.json .; cd .. 
mkdir Homalodisca_vitripennis; cd Homalodisca_vitripennis; cp /app/data/BCM_i5k_pilot/homvit/jbrowse/data/trackList.json .; cd .. 
mkdir Hyalella_azteca; cd Hyalella_azteca; cp /app/data/BCM_i5k_pilot/hyaazt/Hazt_2.0.1/jbrowse/data/trackList.json .; cd .. 
mkdir Laodelphax_striatellus; cd Laodelphax_striatellus; cp /app/data/other_species/laostr/ASM333518v2/jbrowse/data/trackList.json .; cd .. 
mkdir Lasioglossum_albipes; cd Lasioglossum_albipes; cp /app/data/other_species/lasalb/jbrowse/data/trackList.json .; cd .. 
mkdir Latrodectus_hesperus; cd Latrodectus_hesperus; cp /app/data/BCM_i5k_pilot/lathes/GCA_000697925.1/jbrowse/data/trackList.json .; cd .. 
mkdir Leptinotarsa_decemlineata; cd Leptinotarsa_decemlineata; cp /app/data/BCM_i5k_pilot/lepdec/Ldec_2.0/jbrowse/data/trackList.json .; cd .. 
mkdir Leptinotarsa_decemlineata_training; cd Leptinotarsa_decemlineata_training; cp /app/data/BCM_i5k_pilot/lepdec/jbrowse/data/trackList.json .; cd .. 
mkdir Limnephilus_lunatus; cd Limnephilus_lunatus; cp /app/data/BCM_i5k_pilot/limlun/jbrowse/data/trackList.json .; cd .. 
mkdir Locusta_migratoria; cd Locusta_migratoria; cp /app/data/other_species/locmig/jbrowse/data//trackList.json .; cd .. 
mkdir Loxosceles_reclusa; cd Loxosceles_reclusa; cp /app/data/BCM_i5k_pilot/loxrec/GCA_001188405.1/jbrowse/data/trackList.json .; cd .. 
mkdir Mamestra_configurata; cd Mamestra_configurata; cp /app/data/other_species/mamcon/GCA_002192655.1/jbrowse/data/trackList.json .; cd .. 
mkdir Manduca_sexta; cd Manduca_sexta; cp /app/data/other_species/mansex/JHU_Msex_v1.0/jbrowse/data/trackList.json .; cd .. 
mkdir Mayetiola_destructor; cd Mayetiola_destructor; cp /app/data/other_species/maydes/jbrowse/data/trackList.json .; cd .. 
mkdir Medauroidea_extradentata; cd Medauroidea_extradentata; cp /app/data/other_species/medext/GCA_003012365.1/jbrowse/data/trackList.json .; cd .. 
mkdir Megachile_rotundata; cd Megachile_rotundata; cp /app/data/other_species/megrot/jbrowse/data/trackList.json .; cd .. 
mkdir Melipona_quadrifasciata; cd Melipona_quadrifasciata; cp /app/data/other_species/melqua/jbrowse/data/trackList.json .; cd .. 
mkdir Microplitis_demolitor; cd Microplitis_demolitor; cp /app/data/other_species/micdem/jbrowse/data/trackList.json .; cd .. 
mkdir Neodiprion_lecontei; cd Neodiprion_lecontei; cp /app/data/other_species/neolec/Nlec1.1/jbrowse/data/trackList.json .; cd .. 
mkdir Neodiprion_lecontei_training; cd Neodiprion_lecontei_training; cp /app/data/other_species/neolec/jbrowse/data/trackList.json .; cd .. 
mkdir Nicrophorus_vespilloides; cd Nicrophorus_vespilloides; cp /app/data/other_species/nicves/jbrowse/data/trackList.json .; cd .. 
mkdir Nylanderia_fulva; cd Nylanderia_fulva; cp /app/data/other_species/nylful/TAMU_Nfulva_1.0/jbrowse/data/trackList.json .; cd .. 
mkdir Odontomachus_brunneus; cd Odontomachus_brunneus; cp /app/data/other_species/odobru/Obru_v1/jbrowse/data/trackList.json .; cd .. 
mkdir Oncopeltus_fasciatus; cd Oncopeltus_fasciatus; cp /app/data/BCM_i5k_pilot/oncfas/jbrowse/data/trackList.json .; cd .. 
mkdir Oncopeltus_fasciatus_training; cd Oncopeltus_fasciatus_training; cp /app/data/BCM_i5k_pilot/oncfas/jbrowse/data/trackList.json .; cd .. 
mkdir Onthophagus_taurus; cd Onthophagus_taurus; cp /app/data/BCM_i5k_pilot/onttau/jbrowse/data/trackList.json .; cd .. 
mkdir Orussus_abietinus; cd Orussus_abietinus; cp /app/data/BCM_i5k_pilot/oruabi/BCM/jbrowse/data/trackList.json .; cd .. 
mkdir Osmia_lignaria; cd Osmia_lignaria; cp /app/data/other_species/osmlig/USDA_OLig_1.0/jbrowse/data/trackList.json .; cd .. 
mkdir Pachypsylla_venusta; cd Pachypsylla_venusta; cp /app/data/BCM_i5k_pilot/pacven/jbrowse/data/trackList.json .; cd .. 
mkdir Parasteatoda_tepidariorum; cd Parasteatoda_tepidariorum; cp /app/data/BCM_i5k_pilot/partep/jbrowse/data/trackList.json .; cd .. 
mkdir Photinus_pyralis; cd Photinus_pyralis; cp /app/data/other_species/phopyr/Ppyr1.3/jbrowse/data/trackList.json .; cd .. 
mkdir Rhagoletis_zephyria; cd Rhagoletis_zephyria; cp /app/data/other_species/rhazep/jbrowse/data/trackList.json .; cd .. 
mkdir Rhipicephalus_microplus; cd Rhipicephalus_microplus; cp /app/data/other_species/rhimic/jbrowse/data/trackList.json .; cd .. 
mkdir Rhyzopertha_dominica; cd Rhyzopertha_dominica; cp /app/data/other_species/rhydom/RdoDt3_tmp/jbrowse/data/trackList.json .; cd .. 
mkdir Saccharomyceseubayanus; cd Saccharomyceseubayanus; cp /app/data/other_species/saceub/SEUB3.0/jbrowse/data/trackList.json .; cd .. 
mkdir Tigriopus_californicus; cd Tigriopus_californicus; cp /app/data/other_species/tigcal/jbrowse/data/trackList.json .; cd .. 
mkdir Tribolium_castaneum; cd Tribolium_castaneum; cp /app/data/other_species/tricas/jbrowse/data/trackList.json .; cd .. 
mkdir Trichogramma_pretiosum; cd Trichogramma_pretiosum; cp /app/data/BCM_i5k_pilot/tripre/jbrowse/data/trackList.json .; cd .. 
mkdir Varroa_destructor; cd Varroa_destructor; cp /app/data/other_species/vardes/Vdes_3.0/jbrowse/data/trackList.json .; cd .. 
mkdir Varroa_jacobsoni; cd Varroa_jacobsoni; cp /app/data/other_species/varjac/vjacob_1.0/jbrowse/data/trackList.json .; cd .. 
