mkdir 10_-_Onthophagus_taurus_training; cd 10_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 12_-_Onthophagus_taurus_training; cd 12_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 14_-_Onthophagus_taurus_training; cd 14_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 16_-_Onthophagus_taurus_training; cd 16_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 18_-_Onthophagus_taurus_training; cd 18_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 1_-_Onthophagus_taurus_training; cd 1_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 21_-_Onthophagus_taurus_training; cd 21_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 23_-_Onthophagus_taurus_training; cd 23_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 25_-_Onthophagus_taurus_training; cd 25_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 27_-_Onthophagus_taurus_training; cd 27_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 29_-_Onthophagus_taurus_training; cd 29_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 30_-_Onthophagus_taurus_training; cd 30_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 32_-_Onthophagus_taurus_training; cd 32_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 34_-_Onthophagus_taurus_training; cd 34_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 36_-_Onthophagus_taurus_training; cd 36_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 38_-_Onthophagus_taurus_training; cd 38_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 3_-_Onthophagus_taurus_training; cd 3_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 4_-_Onthophagus_taurus_training; cd 4_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 6_-_Onthophagus_taurus_training; cd 6_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir 8_-_Onthophagus_taurus_training; cd 8_-_Onthophagus_taurus_training; cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json .; cd .. 
mkdir Aethina_tumida; cd Aethina_tumida; cp /app/data/other_species/aettum/jbrowse/data/trackList.json .; cd .. 
mkdir Anoplophora_glabripennis; cd Anoplophora_glabripennis; cp /app/data/BCM_i5k_pilot/anogla/BCM/jbrowse/data/trackList.json .; cd .. 
mkdir Athalia_rosae; cd Athalia_rosae; cp /app/data/BCM_i5k_pilot/athros/BCM/jbrowse/data/trackList.json .; cd .. 
mkdir Bactrocera_dorsalis; cd Bactrocera_dorsalis; cp /app/data/other_species/bacdor/jbrowse/data/trackList.json .; cd .. 
mkdir Blattella_germanica; cd Blattella_germanica; cp /app/data/BCM_i5k_pilot/blager/BCM/jbrowse/data/trackList.json .; cd .. 
mkdir Bombus_terrestris; cd Bombus_terrestris; cp /app/data/other_species/bomter/Bter_1.0/jbrowse/data/trackList.json .; cd .. 
mkdir Catajapyx_aquilonaris; cd Catajapyx_aquilonaris; cp /app/data/BCM_i5k_pilot/cataqu/jbrowse/data/trackList.json .; cd .. 
mkdir Cephus_cinctus; cd Cephus_cinctus; cp /app/data/other_species/cepcin/Ccin1/jbrowse/data//trackList.json .; cd .. 
mkdir Chelonus_insularis; cd Chelonus_insularis; cp /app/data/other_species/cheins/ASM1335770v1/jbrowse/data/trackList.json .; cd .. 
mkdir Clitarchus_hookeri; cd Clitarchus_hookeri; cp /app/data/other_species/clihoo/jbrowse/data/trackList.json .; cd .. 
mkdir Copidosoma_floridanum; cd Copidosoma_floridanum; cp /app/data/BCM_i5k_pilot/copflo/jbrowse/data/trackList.json .; cd .. 
mkdir Diabrotica_virgifera_training; cd Diabrotica_virgifera_training; cp /app/data/other_species/diavir/Dvir_v2.0_RefSeq/jbrowse/data/trackList.json .; cd .. 
mkdir Diaphorina_citri; cd Diaphorina_citri; cp /app/data/other_species/diacit/jbrowse/data/trackList.json .; cd .. 
mkdir Drosophila_biarmipes; cd Drosophila_biarmipes; cp /app/data/modencode/drobia/Dbia_2.0/jbrowse/data/trackList.json .; cd .. 
mkdir Drosophila_elegans; cd Drosophila_elegans; cp /app/data/modencode/droele/Dele_2.0/jbrowse/data/trackList.json .; cd .. 
mkdir Drosophila_ficusphila; cd Drosophila_ficusphila; cp /app/data/modencode/drofic/Dfic_2.0/jbrowse/data/trackList.json .; cd .. 
mkdir Drosophila_rhopaloa; cd Drosophila_rhopaloa; cp /app/data/modencode/drorho/Drho_2.0/jbrowse/data/trackList.json .; cd .. 
mkdir Dufourea_novaeangliae; cd Dufourea_novaeangliae; cp /app/data/other_species/dufnov/jbrowse/data/trackList.json .; cd .. 
mkdir Eufriesea_mexicana; cd Eufriesea_mexicana; cp /app/data/other_species/eufmex/ASM148370v1/jbrowse/data/trackList.json .; cd .. 
mkdir Eurytemora_affinis; cd Eurytemora_affinis; cp /app/data/BCM_i5k_pilot/euraff/jbrowse/data/trackList.json .; cd .. 
mkdir Fopius_arisanus; cd Fopius_arisanus; cp /app/data/other_species/fopari/jbrowse/data/trackList.json .; cd .. 
mkdir Galleria_mellonella; cd Galleria_mellonella; cp /app/data/other_species/galmel/ASM364042v2/jbrowse/data/trackList.json .; cd .. 
mkdir Habropoda_laboriosa; cd Habropoda_laboriosa; cp /app/data/other_species/hablab/jbrowse/data/trackList.json .; cd .. 
mkdir Heliothis_virescens; cd Heliothis_virescens; cp /app/data/other_species/helvir/jbrowse/data//trackList.json .; cd .. 
mkdir Homalodisca_vitripennis; cd Homalodisca_vitripennis; cp /app/data/BCM_i5k_pilot/homvit/jbrowse/data/trackList.json .; cd .. 
mkdir Ladona_fulva; cd Ladona_fulva; cp /app/data/BCM_i5k_pilot/ladful/jbrowse/data/trackList.json .; cd .. 
mkdir Lasioglossum_albipes; cd Lasioglossum_albipes; cp /app/data/other_species/lasalb/jbrowse/data/trackList.json .; cd .. 
mkdir Leptinotarsa_decemlineata; cd Leptinotarsa_decemlineata; cp /app/data/BCM_i5k_pilot/lepdec/Ldec_2.0/jbrowse/data/trackList.json .; cd .. 
mkdir Limnephilus_lunatus; cd Limnephilus_lunatus; cp /app/data/BCM_i5k_pilot/limlun/jbrowse/data/trackList.json .; cd .. 
mkdir Loxosceles_reclusa; cd Loxosceles_reclusa; cp /app/data/BCM_i5k_pilot/loxrec/GCA_001188405.1/jbrowse/data/trackList.json .; cd .. 
mkdir Mamestra_configurata; cd Mamestra_configurata; cp /app/data/other_species/mamcon/GCA_002192655.1/jbrowse/data/trackList.json .; cd .. 
mkdir Mayetiola_destructor; cd Mayetiola_destructor; cp /app/data/other_species/maydes/jbrowse/data/trackList.json .; cd .. 
mkdir Megachile_rotundata; cd Megachile_rotundata; cp /app/data/other_species/megrot/jbrowse/data/trackList.json .; cd .. 
mkdir Microplitis_demolitor; cd Microplitis_demolitor; cp /app/data/other_species/micdem/jbrowse/data/trackList.json .; cd .. 
mkdir Neodiprion_lecontei_training; cd Neodiprion_lecontei_training; cp /app/data/other_species/neolec/jbrowse/data/trackList.json .; cd .. 
mkdir Nylanderia_fulva; cd Nylanderia_fulva; cp /app/data/other_species/nylful/TAMU_Nfulva_1.0/jbrowse/data/trackList.json .; cd .. 
mkdir Oncopeltus_fasciatus; cd Oncopeltus_fasciatus; cp /app/data/BCM_i5k_pilot/oncfas/jbrowse/data/trackList.json .; cd .. 
mkdir Onthophagus_taurus; cd Onthophagus_taurus; cp /app/data/BCM_i5k_pilot/onttau/jbrowse/data/trackList.json .; cd .. 
mkdir Osmia_lignaria; cd Osmia_lignaria; cp /app/data/other_species/osmlig/USDA_OLig_1.0/jbrowse/data/trackList.json .; cd .. 
mkdir Parasteatoda_tepidariorum; cd Parasteatoda_tepidariorum; cp /app/data/BCM_i5k_pilot/partep/jbrowse/data/trackList.json .; cd .. 
mkdir Rhagoletis_zephyria; cd Rhagoletis_zephyria; cp /app/data/other_species/rhazep/jbrowse/data/trackList.json .; cd .. 
mkdir Rhyzopertha_dominica; cd Rhyzopertha_dominica; cp /app/data/other_species/rhydom/RdoDt3_tmp/jbrowse/data/trackList.json .; cd .. 
mkdir Tribolium_castaneum; cd Tribolium_castaneum; cp /app/data/other_species/tricas/jbrowse/data/trackList.json .; cd .. 
mkdir Varroa_destructor; cd Varroa_destructor; cp /app/data/other_species/vardes/Vdes_3.0/jbrowse/data/trackList.json .; cd .. 
