cp /app/data/other_species/aettum/jbrowse/data/trackList.json Aethina_tumida/
cp /app/data/other_species/aettum/jbrowse/data/tracks.conf Aethina_tumida/
cp /app/data/BCM_i5k_pilot/agrpla/jbrowse/data/trackList.json Agrilus_planipennis/
cp /app/data/BCM_i5k_pilot/agrpla/jbrowse/data/tracks.conf Agrilus_planipennis/
cp /app/data/other_species/amytra/jbrowse/data/trackList.json Amyelois_transitella/
cp /app/data/other_species/amytra/jbrowse/data/tracks.conf Amyelois_transitella/
cp /app/data/BCM_i5k_pilot/anogla/BCM/jbrowse/data/trackList.json Anoplophora_glabripennis/
cp /app/data/BCM_i5k_pilot/anogla/BCM/jbrowse/data/tracks.conf Anoplophora_glabripennis/
cp /app/data/other_species/apimel/Amel_4.5/jbrowse/data//trackList.json Apis_mellifera/
cp /app/data/other_species/apimel/Amel_4.5/jbrowse/data//tracks.conf Apis_mellifera/
cp /app/data/BCM_i5k_pilot/athros/BCM/jbrowse/data/trackList.json Athalia_rosae/
cp /app/data/BCM_i5k_pilot/athros/BCM/jbrowse/data/tracks.conf Athalia_rosae/
cp /app/data/other_species/baccuc/jbrowse/data/trackList.json Bactrocera_cucurbitae/
cp /app/data/other_species/baccuc/jbrowse/data/tracks.conf Bactrocera_cucurbitae/
cp /app/data/other_species/bacdor/jbrowse/data/trackList.json Bactrocera_dorsalis/
cp /app/data/other_species/bacdor/jbrowse/data/tracks.conf Bactrocera_dorsalis/
cp /app/data/other_species/bacole/jbrowse/data/trackList.json Bactrocera_oleae/
cp /app/data/other_species/bacole/jbrowse/data/tracks.conf Bactrocera_oleae/
cp /app/data/other_species/bemtab/jbrowse/data//trackList.json Bemisia_tabaci/
cp /app/data/other_species/bemtab/jbrowse/data//tracks.conf Bemisia_tabaci/
cp /app/data/BCM_i5k_pilot/blager/BCM/jbrowse/data/trackList.json Blattella_germanica/
cp /app/data/BCM_i5k_pilot/blager/BCM/jbrowse/data/tracks.conf Blattella_germanica/
cp /app/data/other_species/bomimp/BIMP_2.1/jbrowse/data//trackList.json Bombus_impatiens/
cp /app/data/other_species/bomimp/BIMP_2.1/jbrowse/data//tracks.conf Bombus_impatiens/
cp /app/data/other_species/bomter/Bter_1.0/jbrowse/data//trackList.json Bombus_terrestris/
cp /app/data/other_species/bomter/Bter_1.0/jbrowse/data//tracks.conf Bombus_terrestris/
cp /app/data/BCM_i5k_pilot/cataqu/jbrowse/data/trackList.json Catajapyx_aquilonaris/
cp /app/data/BCM_i5k_pilot/cataqu/jbrowse/data/tracks.conf Catajapyx_aquilonaris/
cp /app/data/BCM_i5k_pilot/censcu/Cexi_2.0/jbrowse/data//trackList.json Centruroides_sculpturatus/
cp /app/data/BCM_i5k_pilot/censcu/Cexi_2.0/jbrowse/data//tracks.conf Centruroides_sculpturatus/
cp /app/data/other_species/cepcin/Ccin1/jbrowse/data//trackList.json Cephus_cinctus/
cp /app/data/other_species/cepcin/Ccin1/jbrowse/data//tracks.conf Cephus_cinctus/
cp /app/data/BCM_i5k_pilot/cercap/jbrowse/data/trackList.json Ceratitis_capitata/
cp /app/data/BCM_i5k_pilot/cercap/jbrowse/data/tracks.conf Ceratitis_capitata/
cp /app/data/other_species/cheins/ASM1335770v1/jbrowse/data/trackList.json Chelonus_insularis/
cp /app/data/other_species/cheins/ASM1335770v1/jbrowse/data/tracks.conf Chelonus_insularis/
cp /app/data/BCM_i5k_pilot/cimlec/BCM/jbrowse/data/trackList.json Cimex_lectularius/
cp /app/data/BCM_i5k_pilot/cimlec/BCM/jbrowse/data/tracks.conf Cimex_lectularius/
cp /app/data/other_species/clihoo/jbrowse/data/trackList.json Clitarchus_hookeri/
cp /app/data/other_species/clihoo/jbrowse/data/tracks.conf Clitarchus_hookeri/
cp /app/data/other_species/connas/AAFC_CNas_1.1/jbrowse/data/trackList.json Contarinia_nasturtii/
cp /app/data/other_species/connas/AAFC_CNas_1.1/jbrowse/data/tracks.conf Contarinia_nasturtii/
cp /app/data/BCM_i5k_pilot/copflo/Cflo_2.0/jbrowse/data/trackList.json Copidosoma_floridanum/
cp /app/data/BCM_i5k_pilot/copflo/Cflo_2.0/jbrowse/data/tracks.conf Copidosoma_floridanum/
cp /app/data/other_species/diaall/Dall2.0/jbrowse/data/trackList.json Diachasma_alloeum/
cp /app/data/other_species/diaall/Dall2.0/jbrowse/data/tracks.conf Diachasma_alloeum/
cp /app/data/other_species/diacit/jbrowse/data/trackList.json Diaphorina_citri/
cp /app/data/other_species/diacit/jbrowse/data/tracks.conf Diaphorina_citri/
cp /app/data/other_species/diacit_legacy/jbrowse/data/trackList.json Diaphorina_citri_legacy/
cp /app/data/other_species/diacit_legacy/jbrowse/data/tracks.conf Diaphorina_citri_legacy/
cp /app/data/modencode/drobia/Dbia_2.0/jbrowse/data/trackList.json Drosophila_biarmipes/
cp /app/data/modencode/drobia/Dbia_2.0/jbrowse/data/tracks.conf Drosophila_biarmipes/
cp /app/data/modencode/drobip/Dbip_2.0/jbrowse/data/trackList.json Drosophila_bipectinata/
cp /app/data/modencode/drobip/Dbip_2.0/jbrowse/data/tracks.conf Drosophila_bipectinata/
cp /app/data/modencode/droele/Dele_2.0/jbrowse/data/trackList.json Drosophila_elegans/
cp /app/data/modencode/droele/Dele_2.0/jbrowse/data/tracks.conf Drosophila_elegans/
cp /app/data/modencode/droeug/Deug_2.0/jbrowse/data/trackList.json Drosophila_eugracilis/
cp /app/data/modencode/droeug/Deug_2.0/jbrowse/data/tracks.conf Drosophila_eugracilis/
cp /app/data/modencode/drofic/Dfic_2.0/jbrowse/data/trackList.json Drosophila_ficusphila/
cp /app/data/modencode/drofic/Dfic_2.0/jbrowse/data/tracks.conf Drosophila_ficusphila/
cp /app/data/modencode/drokik/Dkik_2.0/jbrowse/data/trackList.json Drosophila_kikkawai/
cp /app/data/modencode/drokik/Dkik_2.0/jbrowse/data/tracks.conf Drosophila_kikkawai/
cp /app/data/modencode/drorho/Drho_2.0/jbrowse/data/trackList.json Drosophila_rhopaloa/
cp /app/data/modencode/drorho/Drho_2.0/jbrowse/data/tracks.conf Drosophila_rhopaloa/
cp /app/data/modencode/drotak/Dtak_2.0/jbrowse/data/trackList.json Drosophila_takahashii/
cp /app/data/modencode/drotak/Dtak_2.0/jbrowse/data/tracks.conf Drosophila_takahashii/
cp /app/data/modencode/Drosophila_eugracilis/jbrowse/data/trackList.json Drosophila_eugracilis/
cp /app/data/modencode/Drosophila_eugracilis/jbrowse/data/tracks.conf Drosophila_eugracilis/
cp /app/data/other_species/dufnov/jbrowse/data/trackList.json Dufourea_novaeangliae/
cp /app/data/other_species/dufnov/jbrowse/data/tracks.conf Dufourea_novaeangliae/
cp /app/data/BCM_i5k_pilot/ephdan/Edan_2.0/jbrowse/data/trackList.json Ephemera_danica/
cp /app/data/BCM_i5k_pilot/ephdan/Edan_2.0/jbrowse/data/tracks.conf Ephemera_danica/
cp /app/data/other_species/eufmex/ASM148370v1/jbrowse/data/trackList.json Eufriesea_mexicana/
cp /app/data/other_species/eufmex/ASM148370v1/jbrowse/data/tracks.conf Eufriesea_mexicana/
cp /app/data/BCM_i5k_pilot/euraff/jbrowse/data/trackList.json Eurytemora_affinis/
cp /app/data/BCM_i5k_pilot/euraff/jbrowse/data/tracks.conf Eurytemora_affinis/
cp /app/data/other_species/fopari/jbrowse/data/trackList.json Fopius_arisanus/
cp /app/data/other_species/fopari/jbrowse/data/tracks.conf Fopius_arisanus/
cp /app/data/BCM_i5k_pilot/fraocc/Focc_3.0/jbrowse/data/trackList.json Frankliniella_occidentalis/
cp /app/data/BCM_i5k_pilot/fraocc/Focc_3.0/jbrowse/data/tracks.conf Frankliniella_occidentalis/
cp /app/data/other_species/galmel/ASM364042v2/jbrowse/data/trackList.json Galleria_mellonella/
cp /app/data/other_species/galmel/ASM364042v2/jbrowse/data/tracks.conf Galleria_mellonella/
cp /app/data/BCM_i5k_pilot/gerbue/BCM/jbrowse/data//trackList.json Gerris_buenoi/
cp /app/data/BCM_i5k_pilot/gerbue/BCM/jbrowse/data//tracks.conf Gerris_buenoi/
cp /app/data/other_species/hablab/jbrowse/data/trackList.json Habropoda_laboriosa/
cp /app/data/other_species/hablab/jbrowse/data/tracks.conf Habropoda_laboriosa/
cp /app/data/BCM_i5k_pilot/halhal/Hhal_1.1/jbrowse/data/trackList.json Halyomorpha_halys/
cp /app/data/BCM_i5k_pilot/halhal/Hhal_1.1/jbrowse/data/tracks.conf Halyomorpha_halys/
cp /app/data/other_species/helvir/jbrowse/data//trackList.json Heliothis_virescens/
cp /app/data/other_species/helvir/jbrowse/data//tracks.conf Heliothis_virescens/
cp /app/data/other_species/holduo/ASM273828v1/jbrowse/data/trackList.json Holacanthella_duospinosa/
cp /app/data/other_species/holduo/ASM273828v1/jbrowse/data/tracks.conf Holacanthella_duospinosa/
cp /app/data/BCM_i5k_pilot/homvit/jbrowse/data/trackList.json Homalodisca_vitripennis/
cp /app/data/BCM_i5k_pilot/homvit/jbrowse/data/tracks.conf Homalodisca_vitripennis/
cp /app/data/BCM_i5k_pilot/hyaazt/Hazt_2.0.1/jbrowse/data/trackList.json Hyalella_azteca/
cp /app/data/BCM_i5k_pilot/hyaazt/Hazt_2.0.1/jbrowse/data/tracks.conf Hyalella_azteca/
cp /app/data/BCM_i5k_pilot/ladful/Lful_2.0/jbrowse/data/trackList.json Ladona_fulva/
cp /app/data/BCM_i5k_pilot/ladful/Lful_2.0/jbrowse/data/tracks.conf Ladona_fulva/
cp /app/data/other_species/laostr/ASM333518v2/jbrowse/data(remove3annotationstochange)/trackList.json Laodelphax_striatellus/
cp /app/data/other_species/laostr/ASM333518v2/jbrowse/data(remove3annotationstochange)/tracks.conf Laodelphax_striatellus/
cp /app/data/other_species/lasalb/jbrowse/data/trackList.json Lasioglossum_albipes/
cp /app/data/other_species/lasalb/jbrowse/data/tracks.conf Lasioglossum_albipes/
cp /app/data/BCM_i5k_pilot/lathes/GCA_000697925.1/jbrowse/data/trackList.json Latrodectus_hesperus/
cp /app/data/BCM_i5k_pilot/lathes/GCA_000697925.1/jbrowse/data/tracks.conf Latrodectus_hesperus/
cp /app/data/BCM_i5k_pilot/lepdec/Ldec_2.0/jbrowse/data/trackList.json Leptinotarsa_decemlineata/
cp /app/data/BCM_i5k_pilot/lepdec/Ldec_2.0/jbrowse/data/tracks.conf Leptinotarsa_decemlineata/
cp /app/data/BCM_i5k_pilot/limlun/Llun_2.0/jbrowse/data/trackList.json Limnephilus_lunatus/
cp /app/data/BCM_i5k_pilot/limlun/Llun_2.0/jbrowse/data/tracks.conf Limnephilus_lunatus/
cp /app/data/other_species/locmig/jbrowse/data//trackList.json Locusta_migratoria/
cp /app/data/other_species/locmig/jbrowse/data//tracks.conf Locusta_migratoria/
cp /app/data/BCM_i5k_pilot/loxrec/Lrec_1.0/jbrowse/data/trackList.json Loxosceles_reclusa/
cp /app/data/BCM_i5k_pilot/loxrec/Lrec_1.0/jbrowse/data/tracks.conf Loxosceles_reclusa/
cp /app/data/other_species/mamcon/GCA_002192655.1/jbrowse/data/trackList.json Mamestra_configurata/
cp /app/data/other_species/mamcon/GCA_002192655.1/jbrowse/data/tracks.conf Mamestra_configurata/
cp /app/data/other_species/mansex/jbrowse/data/trackList.json Manduca_sexta/
cp /app/data/other_species/mansex/jbrowse/data/tracks.conf Manduca_sexta/
cp /app/data/other_species/maydes/jbrowse/data/trackList.json Mayetiola_destructor/
cp /app/data/other_species/maydes/jbrowse/data/tracks.conf Mayetiola_destructor/
cp /app/data/other_species/medext/GCA_003012365.1/jbrowse/data/trackList.json Medauroidea_extradentata/
cp /app/data/other_species/medext/GCA_003012365.1/jbrowse/data/tracks.conf Medauroidea_extradentata/
cp /app/data/other_species/megrot/jbrowse/data/trackList.json Megachile_rotundata/
cp /app/data/other_species/megrot/jbrowse/data/tracks.conf Megachile_rotundata/
cp /app/data/other_species/melqua/jbrowse/data/trackList.json Melipona_quadrifasciata/
cp /app/data/other_species/melqua/jbrowse/data/tracks.conf Melipona_quadrifasciata/
cp /app/data/other_species/micdem/jbrowse/data/trackList.json Microplitis_demolitor/
cp /app/data/other_species/micdem/jbrowse/data/tracks.conf Microplitis_demolitor/
cp /app/data/other_species/apimel/Amel_HAv3.1/jbrowse/data/trackList.json Monica_testing/
cp /app/data/other_species/apimel/Amel_HAv3.1/jbrowse/data/tracks.conf Monica_testing/
cp /app/data/other_species/neolec/Nlec1.1/jbrowse/data//trackList.json Neodiprion_lecontei/
cp /app/data/other_species/neolec/Nlec1.1/jbrowse/data//tracks.conf Neodiprion_lecontei/
cp /app/data/other_species/neolec/jbrowse/data/trackList.json Neodiprion_lecontei_training/
cp /app/data/other_species/neolec/jbrowse/data/tracks.conf Neodiprion_lecontei_training/
cp /app/data/other_species/nicves/jbrowse/data/trackList.json Nicrophorus_vespilloides/
cp /app/data/other_species/nicves/jbrowse/data/tracks.conf Nicrophorus_vespilloides/
cp /app/data/other_species/nylful/TAMU_Nfulva_1.0/jbrowse/data/trackList.json Nylanderia_fulva/
cp /app/data/other_species/nylful/TAMU_Nfulva_1.0/jbrowse/data/tracks.conf Nylanderia_fulva/
cp /app/data/other_species/odobru/Obru_v1/jbrowse/data/trackList.json Odontomachus_brunneus/
cp /app/data/other_species/odobru/Obru_v1/jbrowse/data/tracks.conf Odontomachus_brunneus/
cp /app/data/BCM_i5k_pilot/oncfas/BCM/jbrowse/data/trackList.json Oncopeltus_fasciatus/
cp /app/data/BCM_i5k_pilot/oncfas/BCM/jbrowse/data/tracks.conf Oncopeltus_fasciatus/
cp /app/data/BCM_i5k_pilot/oncfas/jbrowse/data/trackList.json Oncopeltus_fasciatus_training/
cp /app/data/BCM_i5k_pilot/oncfas/jbrowse/data/tracks.conf Oncopeltus_fasciatus_training/
cp /app/data/BCM_i5k_pilot/onttau/jbrowse/data/trackList.json Onthophagus_taurus/
cp /app/data/BCM_i5k_pilot/onttau/jbrowse/data/tracks.conf Onthophagus_taurus/
cp /app/data/BCM_i5k_pilot/oruabi/BCM/jbrowse/data/trackList.json Orussus_abietinus/
cp /app/data/BCM_i5k_pilot/oruabi/BCM/jbrowse/data/tracks.conf Orussus_abietinus/
cp /app/data/other_species/osmlig/USDA_OLig_1.0/jbrowse/data/trackList.json Osmia_lignaria/
cp /app/data/other_species/osmlig/USDA_OLig_1.0/jbrowse/data/tracks.conf Osmia_lignaria/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_10/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_10/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_11/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_11/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_12/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_12/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_13/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_13/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_14/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_14/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_15/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_15/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_16/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_16/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_17/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_17/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_18/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_18/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_19/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_19/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_1/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_1/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_20/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_20/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_21/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_21/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_22/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_22/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_23/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_23/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_24/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_24/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_25/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_25/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_26/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_26/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_27/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_27/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_28/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_28/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_29/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_29/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_2/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_2/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_30/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_30/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_31/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_31/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_32/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_32/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_33/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_33/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_34/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_34/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_35/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_35/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_36/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_36/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_37/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_37/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_38/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_38/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_39/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_39/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_3/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_3/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_40/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_40/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_4/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_4/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_5/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_5/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_6/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_6/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_7/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_7/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_8/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_8/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/trackList.json O._taurus_training_9/
cp /app/data/BCM_i5k_pilot/onttau_training/jbrowse/data/tracks.conf O._taurus_training_9/
cp /app/data/BCM_i5k_pilot/pacven/jbrowse/data/trackList.json Pachypsylla_venusta/
cp /app/data/BCM_i5k_pilot/pacven/jbrowse/data/tracks.conf Pachypsylla_venusta/
cp /app/data/BCM_i5k_pilot/partep/Ptep_2.0/jbrowse/data/trackList.json Parasteatoda_tepidariorum/
cp /app/data/BCM_i5k_pilot/partep/Ptep_2.0/jbrowse/data/tracks.conf Parasteatoda_tepidariorum/
cp /app/data/other_species/rhazep/jbrowse/data/trackList.json Rhagoletis_zephyria/
cp /app/data/other_species/rhazep/jbrowse/data/tracks.conf Rhagoletis_zephyria/
cp /app/data/other_species/rhydom/RdoDt3_tmp/jbrowse/data/trackList.json Rhyzopertha_dominica/
cp /app/data/other_species/rhydom/RdoDt3_tmp/jbrowse/data/tracks.conf Rhyzopertha_dominica/
cp /app/data/other_species/tesmon/Amel_HAv3.1/jbrowse/data/trackList.json Test_Monica/
cp /app/data/other_species/tesmon/Amel_HAv3.1/jbrowse/data/tracks.conf Test_Monica/
cp /app/data/other_species/tigcal/jbrowse/data/trackList.json Tigriopus_californicus/
cp /app/data/other_species/tigcal/jbrowse/data/tracks.conf Tigriopus_californicus/
cp /app/data/other_species/tricas/jbrowse/data/trackList.json Tribolium_castaneum/
cp /app/data/other_species/tricas/jbrowse/data/tracks.conf Tribolium_castaneum/
cp /app/data/BCM_i5k_pilot/tripre/jbrowse/data/trackList.json Trichogramma_pretiosum/
cp /app/data/BCM_i5k_pilot/tripre/jbrowse/data/tracks.conf Trichogramma_pretiosum/
cp /app/data/other_species/monpoe/Amel_4.5/jbrowse/data/trackList.json Tuesdays_test/
cp /app/data/other_species/monpoe/Amel_4.5/jbrowse/data/tracks.conf Tuesdays_test/
cp /app/data/other_species/vardes/Vdes_3.0/jbrowse/data/trackList.json Varroa_destructor/
cp /app/data/other_species/vardes/Vdes_3.0/jbrowse/data/tracks.conf Varroa_destructor/
cp /app/data/other_species/varjac/vjacob_1.0/jbrowse/data/trackList.json Varroa_jacobsoni/
cp /app/data/other_species/varjac/vjacob_1.0/jbrowse/data/tracks.conf Varroa_jacobsoni/
